import { useLang } from "../../contexts/LangContext";

// Domain-local text: the shared dictionary baseline remains untouched.
const TEXT = {
  pattern: ["Pattern", "模式匹配", "模式匹配"],
  explicit_group: ["Explicit group", "明確群組", "显式群组"],
  mode: ["Route mode", "路由模式", "路由模式"],
  sources: ["Source models", "來源模型", "来源模型"],
  sourceSearch: ["Search source models", "搜尋來源模型", "搜索来源模型"],
  publicName: ["Public model name", "對外模型名稱", "对外模型名称"],
  sourcesHint: ["Choose exact source routes. Channels remain owned by their source routes.", "選擇精確來源路由。頻道仍由來源路由管理。", "选择精确来源路由。通道仍由来源路由管理。"],
  groupHint: ["Group channels are inherited. Edit bindings, priorities and weights on the source route.", "群組頻道繼承自來源。請在來源路由編輯綁定、優先序與權重。", "群组通道继承自来源。请在来源路由编辑绑定、优先级与权重。"],
  openSource: ["Open source route", "開啟來源路由", "打开来源路由"],
  priority: ["Priority bucket", "優先序分組", "优先级分组"],
  weight: ["Weight", "權重", "权重"],
  binding: ["Token binding", "令牌綁定", "令牌绑定"],
  follow: ["Use account default", "使用帳號預設令牌", "使用账号默认令牌"],
  followHint: ["Resolves the current account default when saved.", "儲存時解析帳號目前的預設令牌。", "保存时解析账号当前的默认令牌。"],
  editChannel: ["Edit channel", "編輯頻道", "编辑通道"],
  moveUp: ["Move priority bucket up", "上移優先序分組", "上移优先级分组"],
  moveDown: ["Move priority bucket down", "下移優先序分組", "下移优先级分组"],
  bucketHint: ["Equal priorities share a bucket. Moving a bucket preserves ties; edit a priority to split or merge.", "相同優先序共用分組。移動分組保留並列；編輯優先序可拆分或合併。", "相同优先级共用分组。移动分组保留并列；编辑优先级可拆分或合并。"],
  status: ["Status", "狀態", "状态"],
  site: ["Site", "站點", "站点"],
  brand: ["Brand", "品牌", "品牌"],
  capability: ["Capability", "能力", "能力"],
  group: ["Group", "群組", "群组"],
  other: ["Other", "其他", "其他"],
  all: ["All", "全部", "全部"],
  nameSort: ["Name A–Z", "名稱 A–Z", "名称 A–Z"],
  nameDesc: ["Name Z–A", "名稱 Z–A", "名称 Z–A"],
  channelSort: ["Most channels", "頻道最多", "通道最多"],
  sort: ["Sort", "排序", "排序"],
  refresh: ["Refresh", "重新整理", "刷新"],
  refreshDecisions: ["Refresh cached probabilities", "重新整理快取概率", "刷新缓存概率"],
  task: ["Refresh task", "重新整理任務", "刷新任务"],
  queued: ["Queued", "已排程", "已排队"],
  pending: ["Pending", "等待中", "等待中"],
  running: ["Running", "執行中", "执行中"],
  succeeded: ["Completed", "已完成", "已完成"],
  failed: ["Failed", "失敗", "失败"],
  cancelled: ["Cancelled", "已取消", "已取消"],
  selection: ["Selection probability", "選取概率", "选中概率"],
  eligible: ["Eligible", "可用", "可用"],
  ineligible: ["Ineligible", "不可用", "不可用"],
  noDecision: ["No decision available. Retry to obtain backend diagnostics.", "沒有可用決策。請重試以取得後端診斷。", "没有可用决策。请重试以获取后端诊断。"],
  cached: ["Cached decision", "快取決策", "缓存决策"],
  liveDecision: ["Live decision", "即時決策", "实时决策"],
  routeWide: ["Whole-route decision", "整條路由決策", "整条路由决策"],
  concrete: ["Concrete model (optional)", "具體模型（選填）", "具体模型（可选）"],
  inspect: ["Inspect decision", "檢查決策", "检查决策"],
  saved: ["Saved", "已儲存", "已保存"],
  error: ["Operation failed", "操作失敗", "操作失败"],
  invalidRoute: ["Provide a model pattern, or a public name and at least one source model for a group.", "請填寫模型模式；群組須填寫對外名稱並選擇至少一個來源模型。", "请填写模型模式；群组须填写对外名称并选择至少一个来源模型。"],
  invalidStrategy: ["Select a supported strategy.", "請選擇支援的策略。", "请选择支持的策略。"],
  invalidChannel: ["Priority must be a nonnegative integer and weight a finite nonnegative number.", "優先序須為非負整數，權重須為有限非負數。", "优先级须为非负整数，权重须为有限非负数。"],
  deleteRoute: ["Delete this route?", "刪除此路由？", "删除此路由？"],
  deleteChannel: ["Remove this channel?", "移除此頻道？", "移除此通道？"],
  emptyChannels: ["No channels. This route cannot forward traffic.", "沒有頻道，此路由無法轉發流量。", "没有通道，此路由无法转发流量。"],
  globHint: ["Glob pattern, for example gpt-*", "Glob 模式，例如 gpt-*", "Glob 模式，例如 gpt-*"],
  weighted: ["Weighted", "加權隨機", "加权随机"],
  round_robin: ["Round robin", "輪詢", "轮询"],
  stable_first: ["Stable first", "穩定優先", "稳定优先"],
  selected: ["selected", "已選取", "已选择"],
  clear: ["Clear", "清除", "清除"],
  rebuild: ["Rebuild", "重建", "重建"],
  rebuildQueued: ["Rebuild requested; refresh to check the routes.", "已請求重建，請重新整理查看路由。", "已请求重建，请刷新查看路由。"],
  missingToken: ["Current token (unavailable in picker)", "目前令牌（選單中不可用）", "当前令牌（选单中不可用）"],
  retryTask: ["Retry task status", "重試任務狀態", "重试任务状态"],
} as const;
export type RoutesTextKey = keyof typeof TEXT;
export function useRoutesText() {
  const {lang} = useLang();
  const index = lang === "zh-Hant" ? 1 : lang === "zh-Hans" ? 2 : 0;
  return (key:RoutesTextKey):string => TEXT[key][index];
}
