replicaCount: 1

image:
  repository: 1467078763/metapi
  tag: latest
  digest: ""
  pullPolicy: Always

service:
  type: NodePort
  port: 4000
  nodePort: 30400

deployment:
  strategy:
    maxSurge: 1
    maxUnavailable: 0

persistence:
  hostPath: /opt/1panel/docker/compose/metapihub/data

existingSecret: ""

env:
  authToken: ""
  proxyToken: ""
  dbType: postgres
  dbUrl: ""
  dbSsl: "false"
  dataDir: /app/data
  port: "4000"
  tz: Asia/Shanghai
  checkinCron: "0 8 * * *"
  balanceRefreshCron: "0 * * * *"
  deployHelperToken: ""
  geminiCliClientId: ""
  geminiCliClientSecret: ""
  antigravityClientId: ""
  antigravityClientSecret: ""
