import { useState } from 'react';
import { EditDrawer, Field, TextInput } from '../../components/EditDrawer';
import { apiPost } from '../../lib/client';
import { batchOutcome, type BatchResponse } from '../../lib/managementParity';
import { useManagementText } from '../../lib/managementParityText';
import { useToast } from '../../components/Toast';
export default function KeyMetadata({ ids, onClose, onSaved }: { ids: number[]; onClose: () => void; onSaved: (failedIds: number[]) => Promise<void> }) {
  const l = useManagementText(); const { showToast } = useToast(); const [groupOperation, setGroupOperation] = useState<'keep' | 'set' | 'clear'>('keep'); const [group, setGroup] = useState(''); const [tagOperation, setTagOperation] = useState<'keep' | 'append'>('keep'); const [tags, setTags] = useState(''); const [busy, setBusy] = useState(false);
  const save = async () => { setBusy(true); try { const tagList = tags.split(/[,，\n]/).map(t => t.trim()).filter(Boolean); if ((groupOperation === 'set' && !group.trim()) || (tagOperation === 'append' && !tagList.length)) throw new Error(l('invalid')); const outcome = batchOutcome(await apiPost<BatchResponse>('/api/downstream-keys/batch', { ids, action: 'updateMetadata', groupOperation, ...(groupOperation === 'set' ? { groupName: group.trim() } : {}), tagOperation, ...(tagOperation === 'append' ? { tags: tagList } : {}) })); await onSaved(outcome.failedIds); showToast(`${l('success')}: ${outcome.succeeded}; ${l('failed')}: ${outcome.failedIds.length}${outcome.messages.length ? ` — ${outcome.messages.join('; ')}` : ''}`); if (!outcome.failedIds.length) onClose(); } catch(e) { showToast(e instanceof Error ? e.message : l('saveFailed')); } finally { setBusy(false); } };
  return <EditDrawer open title={l('metadata')} onClose={onClose} footer={<><button onClick={onClose}>{l('cancel')}</button><button disabled={busy || !ids.length} onClick={save}>{l('save')}</button></>}><Field label={l('group')}><select value={groupOperation} onChange={e => setGroupOperation(e.target.value as typeof groupOperation)}>{(['keep', 'set', 'clear'] as const).map(v => <option key={v} value={v}>{l(v)}</option>)}</select>{groupOperation === 'set' && <TextInput value={group} onChange={e => setGroup(e.target.value)} />}</Field><Field label={l('tags')}><select value={tagOperation} onChange={e => setTagOperation(e.target.value as typeof tagOperation)}><option value="keep">{l('keep')}</option><option value="append">{l('append')}</option></select>{tagOperation === 'append' && <TextInput value={tags} onChange={e => setTags(e.target.value)} />}</Field></EditDrawer>;
}
